import { resolve } from "node:path";

/**
 * Where the server half of the hydration lane writes each scenario's markup
 * and the client half reads it (gitignored with node_modules; regenerated by
 * every `bun run test:hydration`).
 */
export const artifactsDir = resolve(process.cwd(), "node_modules/.cache/solid-flow-hydration");

/** File-safe artifact path for a scenario. */
export const artifactPath = (name: string): string =>
  resolve(artifactsDir, `${name.replace(/[^a-z0-9]+/gi, "-")}.html`);
