import { describe, expect, it } from "vitest";

import * as api from "@/index";

// The package's runtime exports, pinned. Adding or removing one is a public
// API decision: update this list in the same commit. Components follow the
// union of React Flow's and Svelte Flow's public components; the renderers,
// wrappers, containers and `*Internal` edges stay internal.
const PUBLIC_RUNTIME_EXPORTS = [
  "Background",
  "BaseEdge",
  "BezierEdge",
  "ConnectionLineType",
  "ConnectionMode",
  "ControlButton",
  "Controls",
  "EdgeLabel",
  "EdgeLabelRenderer",
  "EdgeReconnectAnchor",
  "EdgeToolbar",
  "Handle",
  "MarkerType",
  "MiniMap",
  "MiniMapNode",
  "NodeResizer",
  "NodeToolbar",
  "PanOnScrollMode",
  "Panel",
  "Position",
  "ResizeControl",
  "ResizeControlVariant",
  "SelectionMode",
  "SmoothStepEdge",
  "SolidFlow",
  "SolidFlowProvider",
  "StepEdge",
  "StraightEdge",
  "ViewportPortal",
  "addEdge",
  "connectionKey",
  "createEdgeStore",
  "createNodeStore",
  "createOptimisticEdgeStore",
  "createOptimisticNodeStore",
  "getBezierEdgeCenter",
  "getBezierPath",
  "getConnectedEdges",
  "getEdgeCenter",
  "getIncomers",
  "getNodesBounds",
  "getOutgoers",
  "getSmoothStepPath",
  "getStraightPath",
  "getViewportForBounds",
  "useColorMode",
  "useConnection",
  "useEdge",
  "useEdgeId",
  "useEdges",
  "useInternalNode",
  "useKeyPress",
  "useNode",
  "useNodeConnections",
  "useNodeId",
  "useNodes",
  "useNodesData",
  "useNodesInitialized",
  "useSelectedEdges",
  "useSelectedNodes",
  "useSolidFlow",
  "useUpdateNodeInternals",
  "useViewport",
  "useViewportInitialized",
];

describe("public surface", () => {
  it("exports exactly the public runtime API", () => {
    expect(Object.keys(api).sort()).toEqual([...PUBLIC_RUNTIME_EXPORTS].sort());
  });
});
