import {
  A11y,
  AddNodeOnDrop,
  ColorMode,
  CustomConnectionLine,
  CustomNode,
  DragNDrop,
  Edges,
  HandleConnect,
  Interaction,
  Intersections,
  NodeResizer,
  NodeToolbar,
  Overview,
  Reset,
  StressTest,
  Subflows,
  UpdateNodeInternals,
  UseNodesData,
  UseSolidFlow,
  Validation,
} from "./examples";

export const SolidFlowExamplesMap = {
  A11y,
  AddNodeOnDrop,
  ColorMode,
  CustomConnectionLine,
  CustomNode,
  DragNDrop,
  Edges,
  HandleConnect,
  Interaction,
  Intersections,
  NodeResizer,
  NodeToolbar,
  Overview,
  Reset,
  StressTest,
  Subflows,
  UpdateNodeInternals,
  UseNodesData,
  UseSolidFlow,
  Validation,
} as const;
