import {
  A11y,
  AddNodeOnDrop,
  Backgrounds,
  ColorMode,
  CustomConnectionLine,
  CustomNode,
  Dagre,
  DragNDrop,
  Edges,
  HandleConnect,
  Interaction,
  InteractiveMinimap,
  Intersections,
  NodeResizer,
  NodeToolbar,
  NodeTypeChange,
  Overview,
  Reset,
  StressTest,
  Subflows,
  Switch,
  TwoWayViewport,
  UpdateNodeInternals,
  UseNodesData,
  UseSolidFlow,
  Validation,
} from "./examples";

export const SolidFlowExamplesMap = {
  A11y,
  AddNodeOnDrop,
  Backgrounds,
  ColorMode,
  CustomConnectionLine,
  CustomNode,
  Dagre,
  DragNDrop,
  Edges,
  HandleConnect,
  Interaction,
  InteractiveMinimap,
  Intersections,
  NodeResizer,
  NodeToolbar,
  NodeTypeChange,
  Overview,
  Reset,
  StressTest,
  Subflows,
  Switch,
  TwoWayViewport,
  UpdateNodeInternals,
  UseNodesData,
  UseSolidFlow,
  Validation,
} as const;
